### ISSUE TITLE
Consider using the symbol API to format tooltips better like VS4Mac and ionide

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fsharp-language-server#3]
The build in textual tooltips are pretty horrid for legibility, please consider using the symbol API for format the symbol API results not more legible tooltips.

**Comment by georgewfraser** [comment]
Are you talking about the autocomplete icons? As far as I know there is no API to change these, but there are many built-in icons available, the language server protocol enum is [here](https://github.com/georgewfraser/fsharp-language-server/blob/dc54ac3eb2360c6b877d7000b2ef92eca6c6f4d9/src/LSP/Types.fs#L598).

The code that chooses among the available symbols is [here](https://github.com/georgewfraser/fsharp-language-server/blob/7b2980dcb5debc83a8a815c62daeda4b7e0c0af0/src/FSharpLanguageServer/Conversions.fs#L174). It uses the untyped AST, because that's what's available in the "find symbol" context. It might be worthwhile to write a second function that uses the typed AST to get a more precise symbol in the autocomplete context.

**Comment by georgewfraser** [comment]
Actually, the autocomplete symbol code is [here](https://github.com/georgewfraser/fsharp-language-server/blob/7b2980dcb5debc83a8a815c62daeda4b7e0c0af0/src/FSharpLanguageServer/Conversions.fs#L89).

**Comment by georgewfraser** [comment]
OK, it looks like I should have been using FSharpGlyph instead of FSharp CompletionItemKind.

**Comment by 7sharp9** [comment]
I mean the actual tooltip text.  Take any function with more than a few
params and the text look awful via the textual api.  Look at the same in
vscode/vs4mac and you can see they are formatted over multiple lines
aligning etc.

**Comment by 7sharp9** [comment]
@georgewfraser ^

**Comment by georgewfraser** [comment]
Ohhhh got it. Is the problem autocomplete tooltips, or hover tooltips, or both?

If you feel like working on this, the relevant place to add is [here](https://github.com/georgewfraser/fsharp-language-server/blob/fbfefb7c6c712d36cb52b7a14345ffd5c8d58d56/src/FSharpLanguageServer/TipFormatter.fs#L177) for autocomplete and [here](https://github.com/georgewfraser/fsharp-language-server/blob/9e1a8ef36b0c52f0f2216a721cf5a7dd614ef249/src/FSharpLanguageServer/Conversions.fs#L63) for hover.

**Comment by georgewfraser** [comment]
@7sharp9 What exactly is the problem with the current formatting? If you look at the tooltips in VSCode for typescript, which I view as the reference implementation of good language support, the formatting is very similar:

<img width="672" alt="screen shot 2018-06-10 at 3 06 56 pm" src="https://user-images.githubusercontent.com/1369240/41206860-235f6466-6cc0-11e8-892e-e1569cbc6865.png">

**Comment by 7sharp9** [comment]
The function signature itself is the issue, look at any function with 4 or
5 parameters and the formatting is awful.   In VS4MAC and ionide they are
horizontally formatted so the types and parameter names line up.
