### ISSUE TITLE
Any plans to target .NET Core 3.0?

### ISSUE THREAD

**Issue by PhilT** [fsprojects/fsharp-language-server#66]
Just wondering.

**Comment by PhilT** [comment]
I had a stab at it and it seems to be working although I get the same missing DLL error as in the other issue I mentioned.

**Comment by georgewfraser** [comment]
It's a pretty simple extension, the only potential complexities are around the way it gets packaged as a standalone executable.

**Comment by fgborges** [comment]
@georgewfraser Does it mean the package for emacs? Could you give me more explanation?
I am also interested in upgrading this package for the coming LTS dotnet core.

**Comment by adamnew123456** [comment]
@fgborges I assume it refers to the [new dotnet 3 deployment options](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#compiledeploy), although it doesn't look like these would affect the current build process. Single-file packing is opt-in, and the build scripts already produce native executables since they all use `dotnet publish`.

FWIW, my Emacs configuration seems to be running fine after rebuilding with netcoreapp3.0. There are some cases where it dies due to not being able to find `fsc.exe`, but that's an issue in Buildalyzer and not FSharpLanguageServer.

**Comment by adamnew123456** [comment]
The Buildalyzer thing was a red herring, it turns out that the errors I was seeing had to do with some missing assemblies not being loaded. It only affects netcoreapp3.0 projects due to changes in dotnet core itself as described in https://github.com/dotnet/cli/issues/11504.

I was able to use the workaround described there (adding an explicit reference on the Microsoft.NETCore.App package) but it seems like there should be a way to determine these implied packages from the SDK files.

**Comment by fgborges** [comment]
Thanks. You think that the incompatibility of Biuldalyzer setting and netcore3.0 causes this issue, right? Shall we refresh configuration around Buildalzyer with some correct ways as you tried?

**Comment by adamnew123456** [comment]
I've got a branch up and running at https://github.com/adamnew123456/fsharp-language-server/tree/dotnet-3, which is capable of determining the location of the framework assemblies automatically.

I want to add a unit test before opening a PR, but you can run off that branch currently. The existing unit tests pass on my end and I can open both netcoreapp3 projects as well as netcoreapp2 projects and interact with basic LSP features.

**Comment by fgborges** [comment]
So nice. Thank you!!

**Comment by adamnew123456** [comment]
The PR is in at #70. There are some adjustments to make framework detection work better on Windows and .NET Core 3.1, as well as updates to the VS Code plugin.
